DROP DATABASE IF EXISTS alotest;
CREATE DATABASE alotest;

\c alotest;

CREATE TABLE relatedItems (
  id SERIAL,
  name VARCHAR NOT NULL,
  price INT NOT NULL,
  img VARCHAR NOT NULL,
  cat VARCHAR NOT NULL,
  link VARCHAR NOT NULL
);